# Deep Learning with Tensor Flow

In [1]:
import tensorflow as tf


In [2]:
#creating tenser with tf.constant()
scalar=tf.constant(7)

In [3]:
print(scalar)

tf.Tensor(7, shape=(), dtype=int32)


In [4]:
# Checking Dimesion 
scalar.ndim


0

In [5]:
# create Vector
vector=tf.constant([10,10])

In [6]:
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10])>

In [7]:
 vector.ndim

1

In [8]:
# Create matrix
matrix=tf.constant([[10,7],
                   [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]])>

In [9]:
matrix.ndim

2

In [10]:
# New matrix
new_matrix=tf.constant([[10,7,3],
            [3,4,4]],dtype=tf.float16)
new_matrix

<tf.Tensor: shape=(2, 3), dtype=float16, numpy=
array([[10.,  7.,  3.],
       [ 3.,  4.,  4.]], dtype=float16)>

In [11]:
new_matrix.ndim

2

In [12]:
# creating tenser
tensor=tf.constant([[[1,2,3],
                    [4,5,6]],
                    [[7,8,9],
                     [10,11,12]],
                    [[13,14,15],
                     [16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])>

In [13]:
tensor.ndim

3

In [14]:
# creating tensor with tf.variable

tf1=tf.Variable([10,7])
tf2=tf.constant([10,7])

In [15]:
tf.Variable

tensorflow.python.ops.variables.Variable

In [16]:
tf1,tf2

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7])>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7])>)

In [17]:
 #lets try change in t1 using .assign
    
tf1[0].assign(7)
tf1

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7])>

In [18]:
# creating random tensors
r1=tf.random.Generator.from_seed(42)
r1=r1.normal(shape=(3,2))
r1
r2=tf.random.Generator.from_seed(42)
r2=tf.random.normal(shape=(3,2))
r2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.25556782,  0.02485967],
       [-1.2056504 ,  1.7175131 ],
       [ 0.45081684, -1.4482476 ]], dtype=float32)>

In [19]:
r1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [20]:
r1=tf.random.Generator.from_seed(4)
r1=r1.normal(shape=(3,2))

r2=tf.random.Generator.from_seed(5)
r2=tf.random.normal(shape=(3,2))

# Are they equal
r1,r2, r1==r2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 1.0019137 ,  0.6735137 ],
        [ 0.06987712, -1.4077919 ],
        [ 1.0278524 ,  0.27974114]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.7940091 , -0.6546976 ],
        [ 0.03483772, -0.4182598 ],
        [ 1.0506817 , -0.23936985]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[False, False],
        [False, False],
        [False, False]])>)

In [21]:
r3=tf.random.Generator.from_seed(1)
r3=r3.normal(shape=(3,3))
r3

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 0.43842274, -0.53439844, -0.07710262],
       [ 1.5658046 , -0.1012345 , -0.2744976 ],
       [ 1.4204658 ,  1.2609464 , -0.43640924]], dtype=float32)>

r3=tf.random.Generator.from_seed(1)
r3=r3.normal(shape=(3,3))
r3

In [22]:
r3=tf.random.Generator.from_seed(4)
r3=r3.normal(shape=(3,3))
r3

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 1.0019137 ,  0.6735137 ,  0.06987712],
       [-1.4077919 ,  1.0278524 ,  0.27974114],
       [-0.01347923,  1.845181  ,  0.97061104]], dtype=float32)>

In [23]:
# Shuffle the order

not_shuffled=tf.constant([[10,7],[3,4],[2,5]])
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]])>

In [24]:
# suffle our non-shuffled tensor
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [ 2,  5],
       [10,  7]])>

In [25]:
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 2,  5],
       [ 3,  4]])>

In [26]:
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [10,  7],
       [ 2,  5]])>

In [27]:
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [10,  7],
       [ 2,  5]])>

In [28]:
tf.random.set_seed(42) # global level Random seed
tf.random.shuffle(not_shuffled,seed=42) # operational level random seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]])>

In [29]:
## Others way  to make tensor


In [30]:
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [31]:
tf.zeros([3,4])

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [32]:
tf.zeros(shape=(3,4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [33]:
# convert numpy into tenser

import numpy as np
numpy_A=np.arange(1,25,dtype=np.int32)

In [34]:
numpy_A


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [35]:
A=tf.constant(numpy_A)
A

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])>

In [36]:
A=tf.constant(numpy_A,shape=(2,3,4))
B=tf.constant(numpy_A)
A,B

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]])>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24])>)

In [37]:
A.ndim

3

In [38]:
# shape,Rank,Axis or dimension,Size

rank_4_tensor=tf.zeros(shape=[2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [39]:
rank_4_tensor.ndim

4

In [40]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [41]:
rank_4_tensor.shape

TensorShape([2, 3, 4, 5])

In [42]:
tf.size(rank_4_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=120>

In [43]:
rank_4_tensor.shape[-1]

5

# Indexing tensor

Tensors can be indexed just like Python lists

In [44]:
some_list=[1,2,3,4]
some_list[:2]

[1, 2]

In [45]:
# Now in tensor !st 2 elmt of each dim

rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [46]:
some_list[:1]

[1]

In [47]:
rank_4_tensor[:1,:1,:1]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [48]:
rank_4_tensor[:1,:1,:1,:1]

<tf.Tensor: shape=(1, 1, 1, 1), dtype=float32, numpy=array([[[[0.]]]], dtype=float32)>

In [49]:
rank2_tensor=tf.constant([[10,7],
                         [3,4]])

In [50]:
rank2_tensor.shape

TensorShape([2, 2])

In [51]:
rank2_tensor.ndim

2

In [52]:
 rank2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]])>

In [53]:
some_list,some_list[-1]

([1, 2, 3, 4], 4)

In [54]:
#last item of each of row of our rank2 tensor
rank2_tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4])>

In [55]:
 # Add extra dim

rank3_tensor=rank2_tensor[...,tf.newaxis]

In [56]:
rank3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]])>

In [57]:
# Alternative to tf.newaxis
 
tf.expand_dims(rank2_tensor,axis=-1)

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]])>

In [58]:
tf.expand_dims(rank2_tensor,axis=0)

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]])>

In [59]:
tf.expand_dims(rank2_tensor,axis=1)

<tf.Tensor: shape=(2, 1, 2), dtype=int32, numpy=
array([[[10,  7]],

       [[ 3,  4]]])>

# Manipulating Tensor (tensor operation)

In [60]:
# Basic Operation

# + - * / 

tf1= tf.constant([[10,7],
                 [3,7]])
tf1 +10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 17]])>

In [61]:
tf1

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  7]])>

In [62]:
tf1+10


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 17]])>

In [63]:
tf1+50,  tf1

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[60, 57],
        [53, 57]])>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  7]])>)

In [64]:
tf1 *10 , tf1

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[100,  70],
        [ 30,  70]])>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  7]])>)

In [65]:
tf1 - 10 , tf1

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[ 0, -3],
        [-7, -3]])>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  7]])>)

In [66]:
tf1 / 5 , tf1

(<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
 array([[2. , 1.4],
        [0.6, 1.4]])>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  7]])>)

In [67]:
 # built in fn in TensorFlow

tf.multiply(tf1,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  70]])>

In [68]:
# MAtrix multiplication in tensor flow

print(tf1)



tf.Tensor(
[[10  7]
 [ 3  7]], shape=(2, 2), dtype=int32)


In [69]:
tf.matmul(tf1,tf1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121, 119],
       [ 51,  70]])>

In [70]:
tf2=tf.constant([[[1,2,3],
                 [7,2,1],
                [3,3,3]]])
tf2


<tf.Tensor: shape=(1, 3, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [7, 2, 1],
        [3, 3, 3]]])>

In [71]:
tf3=tf.constant([[[3,5],
                 [6,7],
                 [1,8]]])
tf3

<tf.Tensor: shape=(1, 3, 2), dtype=int32, numpy=
array([[[3, 5],
        [6, 7],
        [1, 8]]])>

In [72]:
tf.matmul(tf2,tf3)

<tf.Tensor: shape=(1, 3, 2), dtype=int32, numpy=
array([[[18, 43],
        [34, 57],
        [30, 60]]])>

In [73]:
# MAtrix multiplication with python operator "@"
tf2 @ tf3

<tf.Tensor: shape=(1, 3, 2), dtype=int32, numpy=
array([[[18, 43],
        [34, 57],
        [30, 60]]])>

In [74]:
tf4=tf.matmul(tf2,tf3)
tf4

<tf.Tensor: shape=(1, 3, 2), dtype=int32, numpy=
array([[[18, 43],
        [34, 57],
        [30, 60]]])>

In [75]:
tf.transpose(tf4)

<tf.Tensor: shape=(2, 3, 1), dtype=int32, numpy=
array([[[18],
        [34],
        [30]],

       [[43],
        [57],
        [60]]])>

In [76]:
# Dot product
x=tf.constant([[1,2],
    [3,4],
    [5,6]])
    
y=tf.constant([[7,8],
   [9,10],
   [11,12]])


In [77]:
x,y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]])>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]])>)

In [78]:
tf.matmul(tf.transpose(x),y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]])>

In [79]:
tf.tensordot(tf.transpose(x),y,axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]])>

In [80]:
 tf.matmul(x,tf.transpose(y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]])>

In [81]:
tf.matmul(x,tf.reshape(y,shape=(2,3 )))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]])>

In [82]:
print("Normal y :")
print(y,"\n")

print("y reshaped to (2,3):" )
print(tf.reshape(y,(2,3)),"\n")

print("y transposed: ")
print(tf.transpose(y))

Normal y :
tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32) 

y reshaped to (2,3):
tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32) 

y transposed: 
tf.Tensor(
[[ 7  9 11]
 [ 8 10 12]], shape=(2, 3), dtype=int32)


In [83]:
tf.matmul(x,tf.transpose(y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]])>

# changing the datatype of a tensor


In [84]:
# tensor with default data type (float 32)

b=tf.constant([1.7,7.4])
b.dtype

tf.float32

In [85]:
c=tf.constant([2,45])
c.dtype

tf.int32

In [86]:
d=tf.cast(b, dtype=tf.float16)
d,d.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>,
 tf.float16)

In [87]:
# change from int32 to float 32

E= tf.cast(c,dtype=tf.float32)
E,E.dtype

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 2., 45.], dtype=float32)>,
 tf.float32)

# Aggregating tensor

In [88]:
# Aggregating tensor= condensing them from multiple values  down to a smaller amount of values

D=tf.constant([-7,-10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10])>

In [89]:
# get the absolute value
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10])>

In [90]:
# create tensor values btw 0 and 100 of size 50
 
E=tf.constant(np.random.randint(0,100,size=50))
E

<tf.Tensor: shape=(50,), dtype=int32, numpy=
array([51, 43, 97, 70, 74, 60, 55, 28, 39, 14, 47, 40, 12, 12, 81, 42, 54,
        9, 11, 63, 32, 76, 98, 37, 92, 97, 34, 96, 13, 14, 84,  1, 79, 40,
       57, 31, 84, 87, 61,  8, 50, 17, 25, 64, 90, 86, 57,  2,  6, 20])>

In [91]:
tf.size(E),E.shape,E.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [92]:
# Min of tensor
tf.reduce_min(E)


<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [93]:
# max
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int32, numpy=98>

In [94]:
#min
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int32, numpy=48>

In [95]:
#sum
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int32, numpy=2440>

In [96]:
np.var(E)

887.88

In [97]:
E=tf.cast(E,dtype=tf.float32)
E,E.dtype

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([51., 43., 97., 70., 74., 60., 55., 28., 39., 14., 47., 40., 12.,
        12., 81., 42., 54.,  9., 11., 63., 32., 76., 98., 37., 92., 97.,
        34., 96., 13., 14., 84.,  1., 79., 40., 57., 31., 84., 87., 61.,
         8., 50., 17., 25., 64., 90., 86., 57.,  2.,  6., 20.],
       dtype=float32)>,
 tf.float32)

In [98]:
#variance
tf.math.reduce_variance(E)

<tf.Tensor: shape=(), dtype=float32, numpy=887.88>

In [99]:
#std
tf.math.reduce_std(E)

<tf.Tensor: shape=(), dtype=float32, numpy=29.797316>

In [100]:
# Find the positional maximum and minimum
tf.random.set_seed(42)
F=tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [101]:
# max psnt

tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [102]:
# Index
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [103]:
#max  value of F
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [104]:
#check Equality

F[tf.argmax(F)]==tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [105]:
# postional min

tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [106]:
#index

F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

## Squeezing a tensor (removing all single dimensions)

In [107]:
# Creating tensor
tf.random.set_seed(42)
G=tf.constant(tf.random.uniform(shape=[50]),shape=(1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 50), dtype=float32, numpy=
array([[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
          0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
          0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
          0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
          0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
          0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
          0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
          0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
          0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
          0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]],
      dtype=float32)>

In [108]:
G.shape,G.ndim

(TensorShape([1, 1, 1, 50]), 4)

In [109]:
G_squeezed=tf.squeeze(G)
G_squeezed,G_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>,
 TensorShape([50]))

## One hot encoding

In [110]:
# create a list of indices

some_list=[0,1,2,3] # could be red.green,blue,black

# one hot encode our list of indices
tf.one_hot(some_list,depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [111]:
# custom value for one hot encoding

tf.one_hot(some_list,depth=4,on_value=" I Love deep Learning",off_value=" I also love AI")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b' I Love deep Learning', b' I also love AI', b' I also love AI',
        b' I also love AI'],
       [b' I also love AI', b' I Love deep Learning', b' I also love AI',
        b' I also love AI'],
       [b' I also love AI', b' I also love AI', b' I Love deep Learning',
        b' I also love AI'],
       [b' I also love AI', b' I also love AI', b' I also love AI',
        b' I Love deep Learning']], dtype=object)>

## Squaring , Log , Square root

In [112]:
# Create a new tensor
H=tf.range(1,10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [113]:
#square

tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])>

In [114]:
# Square root
tf.sqrt(tf.cast(H,dtype=tf.float32),H)

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [115]:
# Find LOg
tf.math.log(tf.cast(H,dtype=tf.float32),H)

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

## Tensor and Numpy

In [116]:
# Creating tensor from numpy

J=tf.constant(np.array([3.,7.,10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [117]:
# converting numpy from tensor

np.array(J),type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [118]:
J.numpy(),type(J.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)

In [119]:
numpy_J=tf.constant(np.array([3.,7.,10,]))
tensor_J=tf.constant([3.,7.,10.])

numpy_J.dtype,tensor_J.dtype

(tf.float64, tf.float32)

# Finding access to Gpu


In [120]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]

In [121]:
tf.config.list_physical_devices("GPU")

[]